products = [{name: 'athletic clothes',
             img: 'athleticclothes.png'},
    {name: 'backpack',img:'backpack.jpg'},
  {name:'bandaid',img:'bandaid.png'},
  {name:'baseball',img:'baseball.jpg'},
{name:'basketball',img:'basketball.jpg'},
{name:'beanie',img:'beanie.jpg'},
{name:'bicycle',img:'bicycle.png'},
{name:'books',img:'books.png'},
{name:'calculator',img:'calculator.jpg'},
{name:'camera',img:'camera.jpg'},
{name:'car',img:'car.jpg'},
{name:'chocolate',img:'chocolate.png'},
{name:'coffee',img:'coffee.jpg'},
{name:'computer',img:'computer.jpg'},
{name:'concert tickets',img:'concerttickets.jpg'},
{name:'cooking pot',img:'cookingpot.jpg'},
{name:'detergent',img:'detergent.jpg'},
{name:'dishes',img:'dishes.jpg'},
{name:'dress',img:'dress.jpg'},
{name:'earphones',img:'earphones.jpg'},
{name:'energybar',img:'energybar.jpg'},
{name:'foundation',img:'foundation.jpg'},
{name:'glasses',img:'glasses.jpg'},
{name:'guitar',img:'guitar.png'},
{name:'headphones',img:'headphones.jpg'},
{name:'jacket',img:'jacket.jpg'},
{name:'jewelry earring',img:'jewelryearring.jpg'},
{name:'keyboard',img:'keyboard.jpg'},
{name:'laptop',img:'laptop.jpg'},
{name:'lipstick',img:'lipstick.jpg'},
{name:'napkin',img:'napkin.jpg'},
{name:'necklace',img:'necklace.jpg'},
{name:'notebook',img:'notebook.png'},
{name:'pants',img:'pants.gif'},
{name:'pen',img:'pen.jpg'},
{name:'pencil',img:'pencil.png'},
{name:'purse',img:'purse.jpg'},
{name:'purse',img:'purse.jpg'},
{name:'ring',img:'ring1.jpg'},
{name:'scarf',img:'scarf.jpg'},
{name:'shirt',img:'shirt.png'},
{name:'shoes',img:'shoes.png'},
{name:'skateboard',img:'stakeboard.jpg'},
{name:'socks',img:'socks.jpg'},
{name:'sunglasses',img:'sunglasses.jpg'},
{name:'swimming suit',img:'swimmingsuit.jpg'},
{name:'tickets',img:'tickets.jpg'},
{name:'tie',img:'tie.jpg'},
{name:'video games',img:'videogames.png'},
{name:'wallet',img:'wallet.jpg'},
{name:'watch',img:'watch.jpg'},
{name:'waterbottle',img:'waterbottle.png'},
{name:'wine',img:'wine.png'},
{name:'yoga mat',img:'yoga-2.jpg'}
];
